spring:
  datasource:
    credit:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://sh-cdb-0auhvizu.sql.tencentcdb.com:62736/loan_test?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
      username: root
      password: db!N70ES65#ac
 # hibernate
  jpa:    database: mysql
    show-sql: true
    format-sql: true
    hibernate:      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy      ddl-auto: validate    properties:      hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect
server:
  port: 8080
  tomcat:
    basedir: E:/DB
    uri-encoding: utf-8
    max-connections: 2000
    max-threads: 2000
logging:
  level:
    root: info
    com.example: debug

